### ISSUE TITLE
Variables in ModMailAutomaticMessage string

### ISSUE THREAD

**Issue by AndreaGennaioli** [eightinfinityyt/atn-modmail#3]
Make it possible to add a variable in the ModMailAutomaticMessage string in config.js so that we can interact with the id and tag of the user who opened the ticket inside it. 

Something like that:
```javascript
ModMailAutomaticMessage: 'Hey {{userMention}}, wait for the STAFF.',
```
or
```javascript
ModMailAutomaticMessage: 'Hey <@{{userId}}>, wait for the STAFF.',
```
or
```javascript
ModMailAutomaticMessage: 'Hey {{userTag}}, wait for the STAFF.',
```

In the code there should be just a simple replace() function.

**Comment by eightinfinityyt** [comment]
Cool feature, will look into it actually. Should be a easy change that will come with help command in 1.1.0 in my opinion as it's a minor change + major change.
